

validation:
  listUrl: https://mocki.io/v1/cf019581-c65d-4a33-a496-06c751fdc377
  clientId: my-client-id
  clientSecret: my-client-secret

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PedidosDB;encrypt=false
    username: sa
    password: YourStrong!Passw0rd

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          wk-set-uri: https://dev-kxpt8dcn-dagj15bx.us-5.auth0.com/.well-known/jwks.json